[functions]
included_files = ["node_modules/.prisma/**", "node_modules/@prisma/**", "prisma/schema.prisma", "prisma/dev.db"]

[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"


